
# SEO settings
title: "Code"
title2: "Rock" # default: ""
description: "Welcome to my technical blog"
keywords: "Python,Blog,Computer Science,success"
url: http://vutsuak16.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io


# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Kaustuv Deolal"
  job      : "Software Engineer"
  bio      : "Serenade through my technical epiphanies"
  thumb    : assets/images/kauthor.jpg 
  email    : vutsuak96@gmail.com
  url      : http://vutsuak16.github.io
  github   : https://github.com/Vutsuak16
  blogger  : http://vutsuak95.blogspot.in/
  facebook : https://www.facebook.com/kaustuv.deolal
  linkedin : https://www.linkedin.com/in/kaustuv16/


gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
